package models;

/*
POJO (Plain Old Java Object) representing a 'Post' resource from the API.
Used by Rest Assured for automatic serialization (Java object -> JSON)
and deserialization (JSON -> Java object).
 */
public class PostModel {
    // Fields corresponding to the JSON structure of the request and response
    private String title;
    private String body;
    private int userId;
    private Integer id; // Integer is used because 'id' is generated by the server and might be null in the request payload

    // --- Constructors ---

    //Constructor for creating a PostModel object (payload) to be SENT in a POST request.
    public PostModel(String title, String body, int userId) {
        this.title = title;
        this.body = body;
        this.userId = userId;
    }

    //Default no-argument constructor.
    //Required by Rest Assured for successful deserialization (converting JSON response back to Java object).
    public PostModel() {
    }

    //--- Getters and Setters (Accessors and Mutators) ---
    //These methods allow Rest Assured to read and write values to the private fields.

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
}
