package models;

/*
POJO (Plain Old Java Object) model
 */
public class PostModel {
    // Fields corresponding to the JSON structure of the request and response
    private String title;
    private String body;
    private int userId;
    private Integer id; // id generated by service

    //Constructor for creating a PostModel object
    public PostModel(String title, String body, int userId) {
        this.title = title;
        this.body = body;
        this.userId = userId;
    }

    //Default constructor - required for successful deserialization
    public PostModel() {
    }

    //Getters and Setters

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId)
    {
        this.userId = userId;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
}
