# Name of pipeline in GitHub Actions
name: Java Maven Tests CI (Docker flow)

on:
  # Run on push
  push:
    # Run for branches
    branches: [ master, main ]
  # Run on pull request
  pull_request:
    # For branches
    branches: [ master, main ]

# Jobs definition
jobs:
  build:
    # Run on the standard Ubuntu virtual machine
    #runs-on: windows-latest
    runs-on: ubuntu-latest

    # Steps for execution
    steps:
      - name: Checkout Repository
        # Action to check out the repository code
        uses: actions/checkout@v4

      #- name: Set up Java 17
        # Action to set up the Java environment
        #uses: actions/setup-java@v4
        #with:
          #java-version: '17'
          #distribution: 'temurin'
          # Enable Maven caching for faster dependency downloads
          #cache: maven

      #- name: Run Maven Tests
        # Execute the tests using the Maven 'test' goal
        # Pass the selenide.headless property to ensure tests run without a GUI
        #run: mvn test -Pdev

      # Build docker image first
      - name: Build Docker Image
        run: docker build -t rest-assured-tests .

      # Connect to Cloudflare WARP to bypass 403 Forbidden errors from GoRest
      # This changes the runner's IP to a trusted Cloudflare exit node
      - name: Install and Connect Cloudflare WARP
        uses: fscarmen/warp-on-actions@v1.1

      # Verify the network status and ensure WARP is active (warp=on)
      - name: Check IP and Cloudflare status
        run: |
          curl -s https://www.cloudflare.com/cdn-cgi/trace
          curl -s https://ifconfig.me

      # Execute tests inside the container
      # We use --network host to share the runner's WARP tunnel with the container
      - name: Run Rest Assured Tests
        #run: docker run --rm -e BASE_URL="https://api.example.com" rest-assured-tests mvn clean test -Pdev
        run: |          
          docker run --rm \
          --network host \
          rest-assured-tests mvn clean test -Pdev

      - name: Final Status Check (Success)
        # This step only runs if the previous 'mvn test' step was successful
        if: success()
        run: echo "Tests passed successfully! Continuous Integration is good."

      - name: Report Failure
        # This step only runs if the tests failed
        if: failure()
        run: echo "Tests failed! Check the test results in the workflow logs."

      - name: Setup Allure
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: all-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history # The action above puts the final report here
